{% set version = '0.6.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-brglm
  version: {{ version|replace("-", "_") }}

source:
  fn: brglm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/brglm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/brglm/brglm_{{ version }}.tar.gz
  sha256: b786db50edc703b1b6a986b1ce13d31aab76fd3c672a6540161b25f5cd57239f


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-profilemodel

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-profilemodel

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('brglm')"           # [not win]
    - "\"%R%\" -e \"library('brglm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.ucl.ac.uk/~ucakiko/index.html
  license: GPL (>= 2)
  summary: Fit generalized linear models with binomial responses using either an adjusted-score
    approach to bias reduction or maximum penalized likelihood where penalization is
    by Jeffreys invariant prior. These procedures return estimates with improved frequentist
    properties (bias, mean squared error) that are always finite even in cases where
    the maximum likelihood estimates are infinite (data separation). Fitting takes place
    by fitting generalized linear models on iteratively updated pseudo-data. The interface
    is essentially the same as 'glm'.  More flexibility is provided by the fact that
    custom pseudo-data representations can be specified and used for model fitting.
    Functions are provided for the construction of confidence intervals for the reduced-bias
    estimates.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: brglm
# Title: Bias Reduction in Binomial-Response Generalized Linear Models
# Version: 0.6.1
# Date: 2017-06-28
# Author: Ioannis Kosmidis <i.kosmidis@ucl.ac.uk>
# Maintainer: Ioannis Kosmidis <i.kosmidis@ucl.ac.uk>
# URL: http://www.ucl.ac.uk/~ucakiko/index.html
# Description: Fit generalized linear models with binomial responses using either an adjusted-score approach to bias reduction or maximum penalized likelihood where penalization is by Jeffreys invariant prior. These procedures return estimates with improved frequentist properties (bias, mean squared error) that are always finite even in cases where the maximum likelihood estimates are infinite (data separation). Fitting takes place by fitting generalized linear models on iteratively updated pseudo-data. The interface is essentially the same as 'glm'.  More flexibility is provided by the fact that custom pseudo-data representations can be specified and used for model fitting. Functions are provided for the construction of confidence intervals for the reduced-bias estimates.
# License: GPL (>= 2)
# Depends: R (>= 2.6.0), profileModel
# Suggests: MASS
# NeedsCompilation: yes
# Packaged: 2017-06-28 21:46:05 UTC; yiannis
# Repository: CRAN
# Date/Publication: 2017-06-29 05:56:44 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
