travis:
  secure:
    BINSTAR_TOKEN: Z9N0PetpYJvF8ytWrMNYxKxKWxR7ghZ+olWS1ZuK5fQZYa33VF1fZY+cr0jRFywWVkedjkf8WlIDARkwMTGaFM4NlghNj2tDu5HuaQ7Q2qyV4ezgur7/VPc0gbLGDGC6OrhZjpG476HirkljQWmlWFpybcnFGUZvQFhdicW6Xd3DIW8uNcMElu2Q8nUaXkGxgJigEBwW0oBwZsUnpwImyvuMp4et3DAe7sZRUrz6bRzEStpgieC3zkx4htSYT4alQENg62rQrtqFHKXhFz8lDTRD8RocZWo77YGgeVPXKC1nl3vFzZ8j9031667VvhUTKawD/ciskGMzEE6INZCXglk9PAcB4uk0m5rgsFByAPDNlD3HZLqRv1glBT1UhO0QcFJv1od1kCZdsOaIQbc+RBCpI+vUEfhvtxIO1+/ZQbmAu70L5fqUJC2UXxpUaAuSdPRf6D0fMCgwHT5GtuH5mygwKLtBsEg6xWkeHbDlJOmJypi1IBQ8Op8rxv62i+HYzVhclMumLp9BIv4WbSDio9EmosljqbmUx0+RwzP91wwKwX9VF9UjaV9KUzxtJ41BBGYWEHZuM1cVbUBRlwePCsF2e/bPgVHhXxvIcK/EfTqut0reeH0S4nriMxC+LjvTAqn6Z0/+p3ZomOCZh7qrCVBojXK9chXhj7rsjClAsuE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
