travis:
  secure:
    BINSTAR_TOKEN: fvV62N9l822DWNSfg3/+vBu6RHPDhBVuNyi+LuSUWmlKEGxzu/TIjIYKCT0up2apyueXAPWshXt8wKk3iqZEFMlZNs0VGzjTd3lsDmvN+bqxe8JEmsZ1Vy0AnIyy8gp2oelRIuBZ+DDLKH1tqNx6JQWlioL1NxyPC5WVwY99N6fIU4qwJRjEJEej3uPb288FbnUFfA0roHfWILYbsXAUwVuD7U73NqNBuYUtwVk0aOjyZtqUI9xRskZ3BdHsiFv7qx5fYnOpqDQ8yGc/BGIl69ZLUa8wkSL9Fn9rxoHMo22X940ZJiBjkS48p3tllqF08nEYG2CVQkZed8bGHI3nmEgbZbsERH69v898Ay64xDtxWXo8fAZ16hjz4xI97cLMF7RdjfOdg37AbRE+xQaHfW9mMq4g5GrZ3rq8oubz2BYhPs2jnpretncwPOSrgzn5zpykfempkV/b8mtD+o+UAZ3nFiCd8fw68ei/GYSD2A/+VhNeVi4uzc+vwfJYEIBQH4z3PosuPn00sNsX6qpO5DdILExPUmDS4WkgvPgJumPrjjWC2ufR5JzaMdVzq4tFdG7kfuMmAtpI6XaeauiekG3D0hzz7pgnW7Z8hlgDZrPzUXrG2qpWgyuWZdYnfr20YtGo6D+ClMkVWt6gWc0WdFbjd4n4wF+grJjTRs5p3s4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
